version: '3'
services:
  redis:
    image: redis:5.0.5-alpine
    container_name: redis-cache
    ports:
      - '6379:6379'
    volumes:
      - '~/redis:/data'
    restart: always

  kakao-api:
    image: 'makehoney/kakao-api:latest'
    container_name: kakao-api
    ports:
      - '13570:13570'
    depends_on:
      - redis
    restart: always

networks:
  default:
    external:
      name: notifier-net

#
#      networks:
#        notifier-net:
#          driver: bridge